<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>RestSrvr</PackageId>
		<Title>RestSrvr</Title>
		<Version>$(VersionNumber)</Version>
		<Description>The RestSrvr library represents a wrapper around .NET's HTTP API to provide a Windows Communication Foundation (WCF) REST like wrapper allowing for cross platform REST Server implementation used by the rest of SanteDB (Linux, Android, IOS, Windows, etc.)</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/restsrvr</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\ServiceError.html" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
</Project>
